### PR TITLE
Feature/support phtml

### PR DESCRIPTION
**Pull request by cstergianos**
With this PR I want to make the testing suite, and especially phpcs and phpmd, to parse and search also phtml files for errors or insufficient code

### CODE REVIEW

**Comment by ArjenMiedema** [comment]
@ksangers I think that's a good reason to start reviewing those files. It can be as easy as removing underscore variables in template files. And yet, this will have impact on a lot of files, but you could either work on them or add `// codingStandardsIgnoreFile` to your template files.

**Comment by ksangers** [comment]
@ArjenMiedema @cstergianos Either way, the phpcs.xml and phpmd.xml files are not configured with how phtml files are structured. I think it would be best to develop a derivative of those files and determine how you think phtml files should be structured.

For example, in most templates something similar to `if ($this->checkSomething($var)): echo "123"; else: echo "321"; endif;` is acceptable due to the nature of templates, but not acceptable in classes.

**Comment by cstergianos** [comment]
> @ArjenMiedema @cstergianos Either way, the phpcs.xml and phpmd.xml files are not configured with how phtml files are structured. I think it would be best to develop a derivative of those files and determine how you think phtml files should be structured.
> 
> For example, in most templates something similar to `if ($this->checkSomething($var)): echo "123"; else: echo "321"; endif;` is acceptable due to the nature of templates, but not acceptable in classes.

That sounds reasonable. Is there something fast we can do to change the XML of these phpcs and phpmd? Is it complicated?

**Comment by ArjenMiedema** [comment]
@ksangers I agree. Maybe it's something that needs to be discussed. Just implemented it manually for a Magento 2 project and did get some useful stuff back. Most however was `Undefined variable $block` and `Using $this outside of class` from PHPStan, which isn't an actual issue with Magento theme files. Although you shouldn't use `$this` in Magento 2 theme files.

@cstergianos can you dig into this a bit more?

**Comment by ksangers** [comment]
@cstergianos I think setting it up should be quite easy. I would create a phpcs-phtml.xml and phpmd-phtml.xml and configure them to be copied like the other xml files. Then add a custom task per file that uses phpcs/phpmd that use the new files as new nodes in the grumphp tasks.

The hardest part will be determining what should be checked and what shouldn'tbe .

**Comment by ksangers** [comment]
Please open a new pull request when you have a different solution for this.

**Pull request closed without merging**
